# User Settings | Edit there as per required

title: Isaac Labs
url: "https://labs.isaacphysics.org"
baseurl: ""

email: contact@isaacphysics.org
author: Isaac Physics
# This description will show up in google search results
# (for index page) etc.
description: >
    Isaac Labs is a showcase blog for upcoming or technical features of Isaac Physics.

# This will what will show against &copy; in the footer
copyright: Isaac Physics
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <b>Isaac</b> <span>Labs</span>, a place to discover and try the latest tools being developed for the <a class="underline different-highlight" href="https://isaacphysics.org">Isaac Physics</a> platform.

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Isaac Labs is a showcase blog for upcoming or technical features of Isaac Physics.

about_footer: true

twitter_username: IsaacPhysics
#github_username: yourgithub
facebook_id: IsaacPhysicsUK

# favicon: true
# favicon_location: "/images/favicon.ico"

profile_picture: /images/isaac-logo.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-51129534-4 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "/images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.me/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
